# Generated by Django 3.2 on 2021-09-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photos',
            field=models.ImageField(default='photos/default.png', help_text='Upload a Category image', upload_to='photos/%Y/%m/%d/', verbose_name='photos'),
        ),
    ]
